//This file was generated by script mkregs.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define KNN_SAMPLE 2
#define COORD_XX 3
#define COORD_DATAX 4
#define COORD_DATAY 5
#define COORD_XY 6
#define DISTANCE_HIGH 7
#define DISTANCE_LOW 8
